### ISSUE TITLE
Tiles: Broken style

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#109]
### Overview of the problem

"buefy": "0.4.0"
"vue": "2.3.3"
**OS/Browser**: Tested on latest Chrome and Firefox

### Description

SASS file _messages.scss contains rules breaking the default tile layout provided by Bulma

### Steps to reproduce

1. Import all buefy sass
a) If you want to be specific import just "~buefy/src/scss/components/_messages"
2. Tiles layout is now broken

### Expected behavior

<img width="1236" alt="capture d ecran 2017-06-20 a 10 11 24" src="https://user-images.githubusercontent.com/15009522/27323198-fb25b04a-55a0-11e7-82a0-e7384402281e.png">

### Actual behavior

<img width="1237" alt="capture d ecran 2017-06-20 a 10 13 13" src="https://user-images.githubusercontent.com/15009522/27323502-11a421fc-55a2-11e7-995a-85bd28903dbd.png">

### Potential fix

``` scss
.message .message-body,
.notification {
    //display: flex;
    align-items: center;
    .icon {
        margin-right: 8px;
        margin-left: -8px;
    }
}
```

Seems to do the trick but we may lose some wanted functionality by doing so.
