### ISSUE TITLE
Modal cancel button

### ISSUE THREAD

**Issue by mikekaranja** [rafaelpimpa/buefy#245]
### Overview of the problem
Hi thanks again for this fantastic library. I have one small issue. I would like to change the background color of the cancel 'X' button. On mobile it sometimes cannot be seen when the modal card covers most of the screen, particularly when the modal is white. I can't seem to figure how to change the color in css, even though I have tried modifying the .modal-close{} css class. Any ideas?

**Comment by Tirke** [comment]
You can use the following selector to style the modal close button :

```css
.modal-close:before, .modal-close:after {
  background-color: #your-color;
}
```

**Comment by mikekaranja** [comment]
thanks a lot Tirke. Let me try it out.

**Comment by mikekaranja** [comment]
Hi Tirke Its Still not changing. I don't quite know why

**Comment by Tirke** [comment]
I've done it on my prod env, will give you a repro when I have time.

**Comment by Tirke** [comment]
Ok my bad I thought you wanted to style the cross.
Simple example for what I think you want :

![Modal with close button bg-color changed](http://i.imgur.com/Hmh3RGe.png)

I simply used :
```css
.modal-close {
   background-color: black;
}
```
