### ISSUE TITLE
Is there a way to configure and disable this feature: "All selections control (Checkbox, Radio, RadioButton and Switch) can now be focused and changed by keyboard"

### ISSUE THREAD

**Issue by pirvanc** [rafaelpimpa/buefy#267]
### Overview of the problem

**Buefy** version: v0.5.0
**Vuejs** version: v2.4.2
**OS/Browser**: Chrome 60.0.3112.101, Mozilla 55.0.2

### Description

Is there a way to configure and disable this feature: "All selections control (Checkbox, Radio, RadioButton and Switch) can now be focused and changed by keyboard" ? Specifically, the style that is being added to the focused control.

For example for: Checkbox or Switch controls.

This feature was introduced in version v0.4.0. The thing it adds some styling for the focused control to make it stand out (shadow, glow kind of thing) and I don't want that. Preferably, I would like to have some control over that: enable / disable it.

This doesn't happen for Bulma components.

### Expected behavior

I would like to be possible to control the focus styling for controls (at least: disable / enabled it).

### Actual behavior

Right now, is not possible to control the focus styling for controls (or at least, I didn't find a way).

**Comment by iwan-wijaya** [comment]
You can override the [styling](https://github.com/rafaelpimpa/buefy/blob/ef4c356b23ff2c2a64c80aa5903100c75dd3d234/src/scss/components/_checkbox.scss#L12)
```scss
/* Using SCSS */
.checkbox {
    &:focus {
        input[type=checkbox] + .check {
            box-shadow: none;
        }
        input[type=checkbox]:checked + .check {
            box-shadow: none;   
        }
    }
}

/* Using CSS */
.checkbox:focus input[type=checkbox] + .check {
  box-shadow: none;
}
.checkbox:focus input[type=checkbox]:checked + .check {
  box-shadow: none;
}


```
