### ISSUE TITLE
Tabs are not responsive

### ISSUE THREAD

**Issue by joannesalfa** [rafaelpimpa/buefy#364]
### Overview of the problem

**Buefy** version: v0.5.3
**Vuejs** version: v2.4.4
**OS/Browser**: Opera

### Description

Menu of tabs aren't responsive

### Steps to reproduce

1. Go to https://buefy.github.io/#/documentation/tabs
2. Open with Inspector 
3. Click an icon ''Toggle device toolbar"'
4. Select Galaxy S5
5. See Layout and it looks like overflowing

[![ugly](https://i.imgur.com/GN8bA52.png)](https://i.imgur.com/GN8bA52.png)

### Expected behavior

It should be collapsed.

### Actual behavior

Ugly horizontal with scrollbar and not responsive.

**Comment by jtommy** [comment]
@joannesalfa Buefy Tabs component is like Bulma Tabs component and that is the official behaviour as you can see. Anyway we are open about new improvements and if you want you can create a PR and we'll review it.

**Comment by joannesalfa** [comment]
Oops, sorry.

**Comment by thenicknash** [comment]
@Jugbot Your solution worked wonderfully! Thank you!

**Comment by thenoelman** [comment]
@Jugbot Where do I place that text in order to see your changes?  Thanks!

**Comment by Jugbot** [comment]
@thenoelman It is just normal css? Should work anywhere. If its not, make sure it is declared after buefy css.

**Comment by GopherJ** [comment]
@jtommy

**Comment by devendra-kumar1** [comment]
Hi,
Thanks , that solution works perfectly.
Do we have a way that we can put angular bracket before and end of tab list and on click it can move ?

**Comment by pmfeo** [comment]
@Jugbot thanks for your solution. It works perfectly on my proyect. 💪

**Comment by knadh** [comment]
For tabs without icons, use this to collapse the tab nav into a simple accordion-like layout.

```css
@media screen and (max-width: 768px) {
  nav.tabs ul {
    display: block;
    text-align: left;
    flex-grow: 1;

    a {
      justify-content: left;
    }
    li.is-active a {
      border: 0;
      border: 1px solid $grey-lighter !important;
    }
  }
}
```

![image](https://user-images.githubusercontent.com/547147/134773558-b9d9a4b5-1957-40dd-8044-f100a65b05cf.png)
