### ISSUE TITLE
Is it possible to remove resize from textarea?

### ISSUE THREAD

**Issue by hetsketch** [rafaelpimpa/buefy#561]
Hi! I'm newbie in using buefy and vue, but I would like to know how to make textarea resizeless. I've tried `.textarea { resize: none;  }`, but with scoped style it doesn't work. Any suggestions?

**Comment by avrong** [comment]
Worked for me. You can try add `!important` rule to `resize` property.
```css
.textarea {
  resize: none !important;
}
```
