### ISSUE TITLE
Table wrapper overflow bug

### ISSUE THREAD

**Issue by Hesto** [rafaelpimpa/buefy#72]
### Overview of the problem

**Buefy** version: [0.3.2]
**Vuejs** version: [2.3.3]
**OS/Browser**: Windows/Chrome

### Description

When using dropdown component in table component, after dropdown collapse under bottom of the table, we can see scrollbar at the right (overflow issue).

The problem is in .table-wrapper:
```scss
.table-wrapper {
    overflow-x: auto;
    margin-bottom: 1.5rem;
    .table {
        margin-bottom: 0;
    }
}
```

fix:
```scss
.table-wrapper {
    overflow-x: visible; //change to visible
    margin-bottom: 1.5rem;
    .table {
        margin-bottom: 0;
    }
}
```
### Steps to reproduce

1. Use table component
2. Insert dropdown component inside table
3. Click on dropdown button to collapse it under table

### Expected behavior

![2](https://cloud.githubusercontent.com/assets/13649507/26456965/edb69ac8-416e-11e7-86a7-fd684e28393d.JPG)

### Actual behavior

![1](https://cloud.githubusercontent.com/assets/13649507/26456977/f6b7ef32-416e-11e7-9311-e4619a6ab374.JPG)
